name: Calculateur Historique Workshop

on:
  schedule:
   
  workflow_dispatch: # Te permet de le lancer à la main pour tester

jobs:
  build-history:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Configurer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Lancer la détection des changements
      run: node checker.js

    - name: Enregistrer les modifications dans le dépôt
      run: |
        git config --global user.name 'GMod Bot'
        git config --global user.email 'bot@github.com'
        git add history.json
        # Le git diff vérifie s'il y a du changement à enregistrer
        if ! git diff --quiet --staged; then
          git commit -m "Mise à jour automatique de l'historique [skip ci]"
          # On fait un pull avec rebase pour récupérer tes modifs du web proprement avant de push
          git pull --rebase origin main
          git push origin main
        else
          console.log "Aucun changement détecté dans la collection."
        fi
